### ISSUE TITLE
AbsorbHealing lua error

### ISSUE THREAD

**Issue by wojas007** [bkader/Skada-Revisited#12]
Hi,
I have the newest version of the addon downloaded and I get these lua errors during boss encounters:
https://i.ibb.co/d4zGNQ2/lua1.png
https://i.ibb.co/jGvLR8p/lua2.png

I hope this can help in a way.

Regards,
Wojas

**Comment by bkader** [comment]
Thanks for reporting this. When was the last time you updated the addon? @wojas007

**Comment by wojas007** [comment]
I saw your update yesterday, but I didn't have time to check it yet

**Comment by bkader** [comment]
No worries, I will keep this ticket open until you test it and let me know if it was fixed or not. Thanks again for reporting this.

**Comment by wojas007** [comment]
Downloaded new version and I got lua errors from different lines:
https://i.ibb.co/r6c332x/lua1.png
https://i.ibb.co/YDT6x69/lua2.png

Off topic:
1. Hunter's snakes from snake trap seem to be bugged somehow. They are shown in a weird way in **DPS, Activity, Damage, Debuffs, Useful damage**:
https://i.ibb.co/xFKdthw/image.png

2. Question regarding scrolling modules to choose (**THIS IS COSMETIC SO YOU CAN JUST IGNORE THIS**):
a. Righ-click on any of Skada windows moves to the scroll list of modules
b. Then scroll down a bit and choose something (for example energy gained because it is near the bottom of the list)
c. Then right-click again to go back to the list of modules - you get back to the top of the list
Wouldn't it be better to go back to the position of module that you chose? Below graph what I mean:
https://i.ibb.co/4P2mGQF/image.png

**Comment by bkader** [comment]
If the update went good yet you still have the error, it means something is wrong with the function. I have rewritten the file a bit, I don't raid that often to test it and testing everything solo on a local server doesn't really help, this is why your feedbacks are really useful, I appreciate it.

So, I have modified the file a bit, [you can get this file](https://pastebin.com/TAGYPv2w), raw file, download and replace the old `modules\AbsorbsHealing.lua` file and give it a test whenever you can, I hope this time is fixed. If not, it would be nice if you remember what exactly happened during the encounter that triggered this error.

As for hunter's snake. They shouldn't appear like on that picture, the should look like
![hunters_snake_trap](https://user-images.githubusercontent.com/4732702/100491037-fee3f980-3120-11eb-9786-1efedaae46af.png)

Sadly, I couldn't find a way to attribute the damage done to the hunter that dropped them. I didn't look into it that much, the problem is just like the absorbs module, the combat log isn't providing enough info about the trap, but whenever possible I will search more.

As for saving where you last scrolled, I will look into it but if it's more code than it should I am afraid I'd have to skip 😞 .. Otherwise, there is always "Sort modes by usage" options on `General options`

**Comment by wojas007** [comment]
1. I will check new Absorbs/Healing.lua as soon as I get the chance to raid (probably sunday or monday evening ; / ). If there's still something wrong I'll try to get logs from raid to have more info what happens.

2. Don't worry about these damn snakes. I only showed you this because I thought you didn't know about it. No need to change anything (at least for me).

3. Scrolling is just cosmetic so no need to do anything here too. This was just a thought : )

Thank you again for quick answers.
Have a nice day!

Wojas

**Comment by wojas007** [comment]
Hey!
@bkader Today I tested new absorbshealing module that you linked above. I didn't get a single lua error connected to skada. Even little freezes went away (probably were connected to the lua error). Problem seems to be fixed then.

Cheers!
Wojas
