### ISSUE TITLE
FPS dropped to 0 in the middle of fight :(

### ISSUE THREAD

**Issue by MaelKoT** [bkader/Skada-Revisited#17]
![image](https://user-images.githubusercontent.com/2527033/102193940-bde43700-3ecd-11eb-8a70-0d7aae3e3424.png)
```
function Skada:MemoryCheck()
    UpdateAddOnMemoryUsage()
    local mem = GetAddOnMemoryUsage("Skada")
    if mem > 30000 then
        self:Print(
            L["Memory usage is high. You may want to reset Skada, and enable one of the automatic reset options."]
        )
    end
end
```
I don't care about addon memory usage, but I'm really worried when, due to memory check function, fps drops to zero :(
![image](https://user-images.githubusercontent.com/2527033/102194661-a0fc3380-3ece-11eb-9f27-1982ee976081.png)

**Comment by bkader** [comment]
Thanks for reporting this, it is fixed now. It should be `Skada:Print` instead of `self:Print`.
As for the `MemoryCheck` function, it is only called out of combat and only in 2 situations:
1. 3 seconds after the log (PLAYER_ENTERING_WORLD).
2. 3 seconds after the combat ends.

I don't know if it was this specific lua error that was causing your FPS drop or the function itself or even something else, but try the fix and let me know.
THanks again.

**Comment by MaelKoT** [comment]
Thanks, now I know when this function is called.
It's just that I specially set in the settings to save a large number of fights (~ 30-40), so that I can view them later, and not accidentally lose anything. I understand, this will take more memory and I don't want to see a warning 3 seconds after each fight ends. Is there anything I can do about this?

**Comment by bkader** [comment]
Well, if you really want to remove that function, the easiest and fasted way to do it is by simply emptying the content of that function, making it look like:
```
function Skada:MemoryCheck() end
```

**Comment by bkader** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/4732702/102206644-3dbdd180-3ecd-11eb-9257-cbc001b4a2e9.png)
@MaelKoT you can update the addon now, you will see this option added instead of modifying the files.
Whenever you have the chance to check if the fps drop is gone let me know please so I can close this issue. For now we will leave it open.

**Comment by bkader** [comment]
It has been already a 7 days, I presume that you didn't have any FPS drop or you didn't have the chance to test it. In either cases, I am closing this issue for now. Thanks a lot for your feedback.
