### ISSUE TITLE
Role/class/spec icons

### ISSUE THREAD

**Issue by wojas007** [bkader/Skada-Revisited#19]
Hey!
I really couldn't fully test newest absorbhealing yet, but I played few fights and it seems to be nice. But nobody had val'anyr and this is what I'm most interested in - discipline priest and other healer with val'anyr. I'll update you as soon as I play full raid.

About the topic:
Sometimes after logging in or joining raid I see red squares instead of role, class or spec icons. In most cases they start appearing properly after some time or after few encounters. THREAT module almost never shows icons properly for me. Is it just mine problem?

And other question - spec icons are copied from talents or is it possible to change how certain spec looks?

**Comment by bkader** [comment]
Hello again @wojas007 !
For Val'anyr, there are 2 spells or buffs, the valnyar one and the blessing of forgotten kings, the first one doesn't absorb at all unless the owner of the mace heals the target. So even if you have the proc and you don't heal it won't absorb unless you heal, for example if you apply Renew, everytime it ticks it proc's the Blessing of... which is the shield that absorbs. So if they have Val'anyr and it proc's, you should only see the blessing and not the mace buff (I mean that looks like the mace).

As for the red icons instead of role/class/spec, I noticed this when there is a delay in catching the combatlog data, other than that it should almost never occur. At least so far I didn't see it.
The spec icons are copied from talents, unless I made a mistake of course or specs had to be tweaked because some icons are similar. The are stored in the **media\textures\icon-specs.tga** file.

**Comment by wojas007** [comment]
About Val'anyr:
Don't worry - I know how it works, but I just wanted to see the numbers, so we can potentially close the other issue.

About red squares:
Relogging or reloading does not help - only time fixes it.
BUT as I said threat module keeps showing red squares even if other modules show proper icons. I'll try to record this and maybe it will help. Unless you have an idea what could cause this.

About icons themselves:
I only thought that warrior fury could use other icon : p Like titan's grip talent one.

**Comment by wojas007** [comment]
something like this
[icon-specs.zip](https://github.com/bkader/Skada-Revisited/files/5698306/icon-specs.zip)

**Comment by bkader** [comment]
Where did you get this pack from? You can use it of course, replace the old file and reload, it'll work just fine 👍

**Comment by wojas007** [comment]
Well I opened the file that was in the folder you mentioned and replaced the warrior's icon myself xD

**Comment by bkader** [comment]
> And where are ROLE icons stored? Because there are 3 possible options: class, spec and ROLE.

The roles aren't storred anywhere. `Interface\LFGFrame\UI-LFG-ICON-PORTRAITROLES`, so basically the Tank, Healer and DPS icons you on LFG.

**Comment by wojas007** [comment]
Ok so if I understand you correctly, then they will only show in dungeons, right?

Btw if you liked that file I uploaded above (spec icons), you can use it of course.

**Comment by bkader** [comment]
After few tests, I noticed the red icon. It is due to the default `UnitGroupRolesAssigned` function that returns sometimes unknown role, so I added `Skada:UnitGroupRolesAssigned`. I hope it will work better this way.
