### ISSUE TITLE
Last update - "Unknown" players seems - to replace regular names

### ISSUE THREAD

**Issue by wojas007** [bkader/Skada-Revisited#25]
Hey @bkader !
I've just finished raiding with latest updates of skada and names of players get replaced with something like this:
![image](https://user-images.githubusercontent.com/55255393/104376784-cdcf5500-5525-11eb-81a8-e7418a47df5d.png)

Before this update I NEVER ever had unknown player on my list. Today during the raid ZERO players were Uknown.
I guess it is connected to this:

https://github.com/bkader/Skada-Revisited/commit/eeb60172b1f2bf03616e4b383a97ef4a877e0bfc#diff-d979dba22e2ec7ad07b0eed6e9a32aed325ae7248dc4a496ffe1eae0dd19a502

Regards,
Wojas

**Comment by bkader** [comment]
Hello @wojas007, thanks again for the report and sorry for his incovenient.
This happened ONLY after this update right? If it's the case, I think the error comes from line **1143** that should be moved down below line **1153**. I am going to move it and I will wait for next time your raid if you don't mind, because I am not raiding lately, so I couldn't test it.

**Comment by wojas007** [comment]
Yes only after this update

**Comment by bkader** [comment]
I rolled back to before the update until I get the chance to test the function.
Thanks again for reporting this and sorry for the issue.

Kind regards,
Kader

_PS: I will keep it open until you tell me if it's fixed or not._

**Comment by wojas007** [comment]
Thank you and don't worry about it.
I'll test it next raid I play.

**Comment by wojas007** [comment]
Fixed
