### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by Zinophobia** [bkader/Skada-Revisited#28]
When making a profile on a character with different windows, example: https://imgur.com/a/gvITLJy the position of the windows is saved when logging other characters on the same account. It puts 2 of the windows at the same position, Example: https://imgur.com/a/5xSsZJP

**Comment by bkader** [comment]
Hi @Zinophobia and thanks for the feedback.
I tested what you just said and for some reason I had absolutely no problem with windows positions at all.
Here is what I did:
1. I created 3 different profiles: `Single`, `Double` and `Triple`, their names means how many windows they have.
2. I switched to all the character I have on the account and attempted to load a profile or copy from an existing one.
3. Result: None of the windows moved.

The only time you might encounter windows reposition is when you disable Skada then enable it back, and as far as I know it is due to the **LibWindow** library, no to Skada itself.

**Comment by MaelKoT** [comment]
Maybe one of his windows embed to ElvUI chat frame throught ElvUI_AddonSkins or smthng like this?

**Comment by bkader** [comment]
> 
> 
> Maybe one of his windows embed to ElvUI chat frame through ElvUI_AddonSkins or smthng like this?

Well his screenshots don't tell much about what UI he is using, stock or ElvUI, so no idea!

**Comment by Zinophobia** [comment]
Hey! 

This is what my UI looks like, tell me if you need more information regarding it. https://imgur.com/a/mmKtzv0

Kind regards

**Comment by Zinophobia** [comment]
Might have solved it? Will wait and see, the "Loot frame" from elvui was at that spot, I don't know if it interferes with it.
