### ISSUE TITLE
TOT/MD usages and targets module

### ISSUE THREAD

**Issue by LogansUA** [bkader/Skada-Revisited#37]
Hey, currently I'm struggling to check whether rogue or hunt spend their TOT/MD correctly. I know about a Buffs window that can show the total usage of TOT/MD's but it's not really what I'm looking for.

Would be awesome to add module that shows the exact amount of TOT/MD's that where used and their targets.

P.S. If you can make some suggestion on how to faster implement it - I probably could help with that, although I'm mostly working with JavaScript (Node.js) I could learn something new :)

**Comment by wojas007** [comment]
Hi,
I'm using DBM spell-timers for tot (together with many different timers) and simpleMD for MD. Unfortunately DBM spell-timers can't show MD in a good way.

HOWEVER,
such module could be really useful. In my opinion it could look like this:
Table of MD/tot source (by player) with number of casts -> and inside every cast could be listed separately based on time used (since start of fight) with target. For example

1. MD nickname1 (4)
2. MD nickname2 (7)
3. ToT nickname3 (3)

And if you click on certain name you see this list:
1. Target1 (time1)
2. Target2 (time2)
3. Target3 (time3)
4. Target4 (time4)

This is just my opinion and if @LogansUA likes it then maybe it could be possible to create this.

Btw is there a way to record/calculate threat redirected?

**Comment by bkader** [comment]
@wojas007 @LogansUA do you mean something like this?
![Screenshot_2](https://user-images.githubusercontent.com/4732702/107852849-2e96c980-6e13-11eb-9f92-cf1eb39864d6.png)

**Comment by wojas007** [comment]
Well this may work for tot, however MD doesn't put buff on target

**Comment by bkader** [comment]
> Well this may work for tot, however MD doesn't put buff on target
Yes, that's the only issue. I have enabled buff sources and debuffs targets for auras module. That's the max I think I can do for it because after all this is a Damage meter, not a cooldowns tracker.

**Comment by wojas007** [comment]
I think the idea was to track buff on source and create table from it. And then maybe inside another table of targets

**Comment by bkader** [comment]
The actuel auras module stores targets only for debuffs. but the one i have now before pushing it uses the same table but sources for buffs and targets for debuffs.

The only availabe path so far is: player > spell > target/source.

There are 2 methods to implement nested levels, i will skip the one that requires data change and move to the one that uses the same current data structure :
- click on player : view spells (currently available).
- clicking on a spell : view source/target (next update)

Morr nesting will require creating few sub modules using the same data in order to separate buff done/received and debuffs done/received but this is a overwhelming and skada won't be skada anymore if you see what i mean.

**Comment by wojas007** [comment]
I understand. I only gave my opinion on author's idea.

**Comment by LogansUA** [comment]
@wojas007 yes, that exact what I was thinking about.

@bkader I understood that this will require additional and maybe not needed effort. Maybe this could be developed as a external Skada module that can be installed separately?
The example that you've shown is kinda what I was thinking but still would be way better to see player -> target/source and damage if possible.

**Comment by bkader** [comment]
> but still would be way better to see player -> target/source and damage if possible.

Almost all modules have that feature, all damage modules, all healing and absorbs modules, CC, dispels, interrupts, resurrects.
Auras module (_aka Buffs & Debuffs_) is the only one that's limited to `Buff: Player>Spells` and `Debuffs: Player>Spells>Targets`.
The next update will unlock the `Buffs: Player > Spell > Sources` and that's everything that will implemented, but spells used to damage are few, buffs received + procs are lots and lots, and I don't think it's a smart idea to make their table bigger than it should.
In the next update like I said, player > spell > sources and the source is only recorded if it's not the player himself/herself.
